<Project>

    <PropertyGroup>
        <RepoDirectory>$(MSBuildThisFileDirectory)</RepoDirectory>
        <RepoKind>GitHub</RepoKind>
        <DisableCodeQuality>True</DisableCodeQuality>
        <!-- Disable warnings about vulnerabilities in transitive dependencies. -->
        <!-- This is generally okay, since this code does not interact with users. -->
        <NoWarn>$(NoWarn);NU1903;NU1904</NoWarn>
    </PropertyGroup>

    <Import Project="eng\Versions.props"/>
    <Import Project="eng\Packaging.props"/>

    <Import Project="src\PostSharp.Engineering.Sdk\BuildOptions.props"/>
    <Import Project="src\PostSharp.Engineering.Sdk\SourceLink.props"/>

</Project>