package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'DebugBuild'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("DebugBuild")) {
    requirements {
        remove {
            equals("env.BuildAgentType", "caravela02")
        }
        add {
            equals("env.BuildAgentType", "caravela03")
        }
    }
}
