// Copyright (c) SharpCrafters s.r.o. See the LICENSE.md file in the root directory of this repository root for details.

using JetBrains.Annotations;
using PostSharp.Engineering.BuildTools.Build;
using System;
using System.IO;
using System.Linq;

namespace PostSharp.Engineering.BuildTools.BillOfMaterials;

[UsedImplicitly]
internal class GenerateThirdPartyNoticesCommand : BaseCommand<GenerateThirdPartyNoticesCommandSettings>
{
    protected override bool ExecuteCore( BuildContext context, GenerateThirdPartyNoticesCommandSettings settings )
    {
        var dependencies = DependencyWalker.FindDependenciesAsync( context ).Result;

        context.Console.WriteMessage( "Dependencies processed. Generating THIRD-PARTY-NOTICES.md..." );

        using var writer = new StreamWriter( Path.Combine( context.RepoDirectory, "THIRD-PARTY-NOTICES.md" ) );

        // Write the prolog.
        writer.WriteLine( "# Third-Party Notices" );
        writer.WriteLine();

        writer.WriteLine(
            $"""
             This file lists and documents the licenses and notices for third-party dependencies of the {context.Product.ProductName} repository.

             > [!WARNING]
             > This file pertains to the entire {context.Product.ProductName} repository. If you find this file in a NuGet package, it does not necessarily mean that the package includes all the dependencies listed here. The relevance of each dependency for any package or tool is specified in the table below.

             > [!WARNING]
             > If we have inadvertently omitted a required notice, please let us know. You can post an issue or email us at <hello@postsharp.net>.

             This file is semi-automatically generated by the `Build.ps1 third-party-notice` command.

             ## List of NuGet Dependencies

             This product has a large number of dependencies, but only a few are included in the end-user products.

             To simplify your impact assessment, we have grouped dependencies into the following categories according to the typical use case of
             the package or tool that uses them:

             - **Default**: These dependencies typically ship with and execute in the end-user product.
             - **Development**: These dependencies are typically used during development only. Note that this may include scenarios that might ship with the end-user product but we consider typical development use cases.

             > [!NOTE]
             > Some dependencies have been intentionally excluded from this list. See the exclusions section below.
             """ );

        // Write the table.
        writer.WriteLine();
        writer.WriteLine();
        writer.WriteLine( "## List of Dependencies" );
        writer.WriteLine();
        writer.WriteLine( "| Package Name | Version | License | Authors | Source Repository | Usage | Referenced By |" );
        writer.WriteLine( "|--------------|----------|-----------|---------|-------------------|-------|---------------|" );

        foreach ( var packageInfo in dependencies.OrderBy( p => p.Name ) )
        {
            var name = packageInfo.Name;

            var versions = packageInfo.Versions.Values
                .Where( x => x.Usage.Any( u => u != DependentPackageUsageKind.Private ) )
                .OrderBy( x => x.Version );

            foreach ( var versionInfo in versions )
            {
                var license = versionInfo.License ?? "Unknown";
                var authors = versionInfo.Owners ?? "Unknown";
                var sourceRepo = versionInfo.SourceRepository ?? "Unknown";
                var usage = string.Join( ", ", versionInfo.Usage.Where( u => u != DependentPackageUsageKind.Private ) );
                var discoveredBy = string.Join( ", ", versionInfo.UsedBy );

                writer.WriteLine( $"| {name} | {versionInfo.Version} | {license} | {authors} | {sourceRepo} | {usage} | {discoveredBy} |" );
            }
        }

        writer.WriteLine();
        writer.WriteLine( "## Exclusions" );
        writer.WriteLine();
        writer.WriteLine( "Dependencies from the following namespaces have been excluded from this declaration:" );
        writer.WriteLine();
        writer.WriteLine( "| Namespace | Justification |" );
        writer.WriteLine( "|-----------|---------------|" );

        foreach ( var exclusion in DependencyWalker.DefaultDependentPackageExclusions
                     .Concat( context.Product.DependentPackageExclusions )
                     .OrderBy( x => x.Namespace ) )

        {
            writer.WriteLine( $"| {exclusion.Namespace.TrimEnd( '.' )} | {exclusion.Justification} |" );
        }

        writer.WriteLine();
        writer.WriteLine( "Additionally, dependencies that are only used to build artifacts from the current repository have also been excluded." );
        writer.WriteLine();

        // Fetch and write license notices.
        if ( !settings.ListOnly )
        {
            writer.WriteLine();
            writer.WriteLine();

            foreach ( var repo in dependencies
                         .SelectMany( x => x.Versions.Values.Select( v => (Package: x, Version: v) ) )
                         .GroupBy( x => x.Version.SourceRepository )
                         .OrderBy( x => x.Key, StringComparer.InvariantCultureIgnoreCase )
                    )
            {
                var consumingPackages = repo.SelectMany( x => x.Version.UsedBy ).Distinct().OrderBy( x => x ).ToList();

                if ( consumingPackages.Count == 0 )
                {
                    // It means that it's only used privately. Do not document.
                    continue;
                }

                LicenceNoticeDownloader.AppendLicenseAndNoticeFilesAsync(
                        context,
                        repo.Key!,
                        repo.Select( x => x.Package.Name ).ToList(),
                        consumingPackages,
                        writer )
                    .Wait();
            }
        }

        context.Console.WriteSuccess( "THIRD-PARTY-NOTICES.md has been generated." );

        return true;
    }
}