// Copyright (c) SharpCrafters s.r.o. See the LICENSE.md file in the root directory of this repository root for details.

using System.IO;

namespace PostSharp.Engineering.BuildTools.Docker;

/// <summary>
/// The implicit first component of a <b>child</b> layer's Dockerfile: it builds <c>FROM ${BASE_IMAGE}</c>,
/// whose default is the parent stem's <c>.Dockerfile</c>. <c>DockerBuild.ps1</c> resolves that stem to the
/// parent's content-hash tag and injects it via <c>--build-arg BASE_IMAGE</c>. The chain root uses
/// <see cref="RootPrologComponent"/> instead.
/// </summary>
internal sealed class ChildPrologComponent : ContainerComponent
{
    private readonly string _baseImageStem;

    public ChildPrologComponent( string baseImageStem )
    {
        this._baseImageStem = baseImageStem;
    }

    public override string Name => "Prolog";

    public override ContainerComponentKind Kind => ContainerComponentKind.Prolog;

    public override void WriteDockerfile( TextWriter writer, ContainerOperatingSystem operatingSystem )
    {
        if ( operatingSystem == ContainerOperatingSystem.Linux )
        {
            writer.WriteLine(
                $$"""
                  # This file is auto-generated by PostSharp.Engineering.

                  ARG BASE_IMAGE={{this._baseImageStem}}.Dockerfile
                  FROM ${BASE_IMAGE}

                  """ );
        }
        else
        {
            writer.WriteLine(
                $$"""
                  # escape=`

                  # This file is auto-generated by PostSharp.Engineering.

                  ARG BASE_IMAGE={{this._baseImageStem}}.Dockerfile
                  FROM ${BASE_IMAGE}

                  # The base image's shell is Windows PowerShell (use full path to avoid HCS issues)
                  SHELL ["C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe", "-Command"]

                  """ );
        }
    }
}
