// Copyright (c) SharpCrafters s.r.o. See the LICENSE.md file in the root directory of this repository root for details.

using System.IO;

namespace PostSharp.Engineering.BuildTools.Docker;

/// <summary>
/// The implicit first component of a <b>root</b> layer's Dockerfile. It builds from the external base image and
/// sets up the base environment. On Windows the base tag is supplied at build time via the
/// <c>WINDOWS_VERSION</c> build-arg (so a single Dockerfile serves both ltsc2025 and ltsc2022). A non-root layer
/// uses <see cref="ChildPrologComponent"/> instead.
/// </summary>
internal sealed class RootPrologComponent : ContainerComponent
{
    private const string _defaultLinuxBaseImage = "ubuntu:22.04";

    private readonly string? _baseImage;

    public RootPrologComponent( string? baseImage = null )
    {
        this._baseImage = baseImage;
    }

    public override string Name => "Prolog";

    public override ContainerComponentKind Kind => ContainerComponentKind.Prolog;

    public override void WriteDockerfile( TextWriter writer, ContainerOperatingSystem operatingSystem )
    {
        if ( operatingSystem == ContainerOperatingSystem.Linux )
        {
            // No escape directive: the Linux components use the default backslash continuation.
            // curl, wget and the ICU/SSL libraries are the prerequisites shared by every Linux component,
            // so they are installed here rather than repeated by each of them.
            writer.WriteLine(
                $$"""
                  # This file is auto-generated by PostSharp.Engineering.

                  # See the OS_IMAGE_REPOSITORY comment in the Windows branch: the base image is a build-arg so
                  # that DockerBuild.ps1 can redirect it to a registry-local mirror without changing this file.
                  ARG OS_IMAGE={{this._baseImage ?? _defaultLinuxBaseImage}}
                  FROM ${OS_IMAGE}

                  # Prepare environment
                  ENV DEBIAN_FRONTEND=noninteractive
                  ENV RUNNING_IN_DOCKER=TRUE

                  # Set locale for consistent behavior regardless of host locale
                  ENV LANG=C.UTF-8
                  ENV LC_ALL=C.UTF-8
                  ENV DOTNET_CLI_UI_LANGUAGE=en

                  # Install the prerequisites shared by the other components
                  RUN apt-get update && apt-get install -y \
                      curl \
                      wget \
                      ca-certificates \
                      libicu70 \
                      libssl3 \
                      && rm -rf /var/lib/apt/lists/*

                  """ );
        }
        else
        {
            // The exact base tag (ltsc2025/ltsc2022) is chosen by DockerBuild.ps1 via --build-arg WINDOWS_VERSION
            // and folded into the content-hash tag.
            // OS_IMAGE_REPOSITORY lets DockerBuild.ps1 build from a copy of the OS image mirrored in the
            // configured registry, which on a LAN agent is far closer than mcr.microsoft.com and is the most
            // expensive download of a from-scratch build. It is a build-arg rather than part of the text, so
            // the Dockerfile -- and therefore the content hash -- is the same whichever source is used, and an
            // image built from the mirror is interchangeable with one built from MCR.
            var baseImage = this._baseImage == null
                ? """
                  ARG WINDOWS_VERSION=ltsc2025
                  ARG OS_IMAGE_REPOSITORY=mcr.microsoft.com/windows/servercore
                  FROM ${OS_IMAGE_REPOSITORY}:${WINDOWS_VERSION}
                  """
                : $$"""
                  ARG OS_IMAGE={{this._baseImage}}
                  FROM ${OS_IMAGE}
                  """;

            writer.WriteLine(
                $$"""
                  # escape=`

                  # This file is auto-generated by PostSharp.Engineering.

                  {{baseImage}}

                  # The initial shell is Windows PowerShell (use full path to avoid HCS issues)
                  SHELL ["C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe", "-Command"]

                  # Prepare environment
                  ENV PSExecutionPolicyPreference=Bypass
                  ENV POWERSHELL_UPDATECHECK=Off
                  ENV TEMP=C:\Temp
                  ENV TMP=C:\Temp
                  ENV RUNNING_IN_DOCKER=TRUE

                  # Set locale for consistent behavior regardless of host locale
                  ENV LANG=C.UTF-8
                  ENV LC_ALL=C.UTF-8
                  ENV DOTNET_CLI_UI_LANGUAGE=en
                  ENV VSLANG=1033

                  # Set base PATH explicitly to avoid issues with expansion
                  ENV PATH="C:\Windows\System32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0"

                  # Enable long path support
                  RUN Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1

                  """ );
        }
    }
}
