<Project>

    <!-- Properties of NuGet packages-->
    <PropertyGroup>
        <Authors>PostSharp Technologies</Authors>
        <PackageProjectUrl>https://github.com/postsharp-ops/PostSharp.Engineering</PackageProjectUrl>
        <PackageTags>PostSharp, Metalama, build</PackageTags>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/postsharp-ops/PostSharp.Engineering</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageReleaseNotes>https://github.com/orgs/metalama/discussions/categories/changelog</PackageReleaseNotes>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <PackageDescription>A multi-repo build orchestrator used by PostSharp Technologies for its products and for Metalama.</PackageDescription>
    </PropertyGroup>

    <!-- Additional content of NuGet packages -->
    <ItemGroup>        
        <None Include="$(MSBuildThisFileDirectory)..\LICENSE.md" Visible="false" Pack="true" PackagePath="" />
    </ItemGroup>

    <Import Project="$(MSBuildThisFileDirectory)\..\src\PostSharp.Engineering.Sdk\PostSharpBranding.props" />
</Project>