// Copyright (c) SharpCrafters s.r.o. See the LICENSE.md file in the root directory of this repository root for details.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace PostSharp.Engineering.BuildTools.ContinuousIntegration.TeamCity
{
    internal class TeamCityProject
    {
        private readonly string? _objectName;
        private readonly string? _projectName;
        private readonly TeamCityBuildConfiguration[] _configurations;
        private readonly string[] _additionalBuildTypes;
        private readonly TeamCityProject[] _subProjects;

        /// <summary>
        /// Gets every build configuration of this project and of its sub-projects.
        /// </summary>
        public IEnumerable<TeamCityBuildConfiguration> AllConfigurations
            => this._configurations.Concat( this._subProjects.SelectMany( p => p._configurations ) );

        /// <summary>
        /// Gets every build configuration together with the package it belongs to. The packages mirror the project
        /// tree -- a sub-project's configurations sit in a package of their own -- so that the directory a file is
        /// in tells you which TeamCity project creates it.
        /// </summary>
        public IEnumerable<(string Package, TeamCityBuildConfiguration Configuration)> ConfigurationsByPackage
            => this._configurations.Select( c => (BuildTypesPackage, c) )
                .Concat(
                    this._subProjects.SelectMany(
                        p => p._configurations.Select( c => ($"{BuildTypesPackage}.{p._objectName}", c) ) ) );

        /// <summary>
        /// Gets the packages that hold the build configurations, which the settings file imports.
        /// </summary>
        public IEnumerable<string> BuildTypePackages
            => this.ConfigurationsByPackage.Select( x => x.Package ).Distinct().OrderBy( x => x, StringComparer.Ordinal );

        /// <summary>
        /// The imports shared by the generated files. Each build-type file is compiled on its own and therefore
        /// needs them as much as the settings file does.
        /// </summary>
        public const string Imports = """
                                      import jetbrains.buildServer.configs.kotlin.*
                                      import jetbrains.buildServer.configs.kotlin.buildFeatures.*
                                      import jetbrains.buildServer.configs.kotlin.buildSteps.*
                                      import jetbrains.buildServer.configs.kotlin.failureConditions.*
                                      import jetbrains.buildServer.configs.kotlin.triggers.*
                                      import jetbrains.buildServer.configs.kotlin.projectFeatures.*
                                      """;

        public const string GeneratedFileHeader = "// This file is automatically generated by `Build.ps1 generate-scripts`.";

        /// <summary>The package, and the directory, that the per-build-type files live in.</summary>
        public const string BuildTypesPackage = "buildTypes";

        public TeamCityProject( TeamCityBuildConfiguration[] configurations, string[] additionalBuildTypes, TeamCityProject[]? subProjects = null )
        {
            this._configurations = configurations;
            this._additionalBuildTypes = additionalBuildTypes;
            this._subProjects = subProjects ?? [];
        }

        public TeamCityProject(
            string objectName,
            string projectName,
            TeamCityBuildConfiguration[] configurations,
            string[] additionalBuildTypes,
            TeamCityProject[]? subProjects = null )
            : this( configurations, additionalBuildTypes, subProjects )
        {
            this._objectName = objectName;
            this._projectName = projectName;
        }

        public void GenerateTeamcityCode( TextWriter writer, bool separateBuildTypeFiles = false )
        {
            // The imports are only meaningful when the build configurations live in those packages; Kotlin rejects
            // an import of a package that does not exist.
            var buildTypesImport = separateBuildTypeFiles
                ? Environment.NewLine + string.Join( Environment.NewLine, this.BuildTypePackages.Select( p => $"import {p}.*" ) )
                : "";

            writer.WriteLine(
                $@"{GeneratedFileHeader}

{Imports}{buildTypesImport}

version = ""2025.11""

project {{
" );

            void WriteProjectBody( TeamCityProject project )
            {
                foreach ( var configuration in project._configurations )
                {
                    writer.WriteLine( $"    buildType({configuration.ObjectName})" );
                }

                foreach ( var configuration in project._additionalBuildTypes )
                {
                    writer.WriteLine( $"    buildType({configuration})" );
                }

                writer.WriteLine();

                var configurationsOrder = string.Join( ',', project._configurations.Select( c => c.ObjectName ).Concat( this._additionalBuildTypes ) );
                writer.WriteLine( $"    buildTypesOrder = arrayListOf({configurationsOrder})" );

                if ( project._subProjects.Length > 0 )
                {
                    writer.WriteLine();

                    foreach ( var subProject in project._subProjects )
                    {
                        writer.WriteLine( $"    subProject({subProject._objectName})" );
                    }

                    writer.WriteLine();
                    var subProjectsOrder = string.Join( ',', project._subProjects.Select( p => p._objectName ) );
                    writer.WriteLine( $"    subProjectsOrder = arrayListOf({subProjectsOrder})" );
                }
            }

            WriteProjectBody( this );

            writer.WriteLine(
                $@"
}}" );

            writer.WriteLine();

            // When the build configurations go to separate files they are not written here; the settings file
            // imports them from the buildTypes package instead.
            if ( !separateBuildTypeFiles )
            {
                foreach ( var configuration in this.AllConfigurations )
                {
                    configuration.GenerateTeamcityCode( writer );
                    writer.WriteLine();
                }
            }

            foreach ( var subProject in this._subProjects )
            {
                writer.WriteLine(
                    $@"object {subProject._objectName} : Project({{

    name = ""{subProject._projectName}""
" );

                WriteProjectBody( subProject );

                writer.WriteLine(
                    $@"
}})" );
            }
        }
    }
}